### ISSUE TITLE
CMake?

### ISSUE THREAD

**Issue by RobLoach** [gfxprim/gfxprim#21]
I saw your video at FOSDEM and am really excited about the project! Had a question...

There are Makefiles, which is great. Would you be open to adding a [CMake](https://cmake.org/) definition file to ease compilation? For builds using cmake, it would make it a lot easier to embed gfxprim within another project, and save from having to build the `config.h` with `./configure`.

**Comment by metan-ucw** [comment]
Why not. We can have both build systems for a while and maybe if cmake ends up being better than what we already have we can switch to that completely.

**Comment by RobLoach** [comment]
Going to close this one. The pre-builds seems pretty complex. I'll keep the branch around, but :shrug:
