### ISSUE TITLE
Widgets: Optional dependency on JSON-C

### ISSUE THREAD

**Issue by RobLoach** [gfxprim/gfxprim#28]
Would be nice to be able to use the Widgets API without needing JSON. While loading from JSON is nice, would be nice to not have it required :wink:

**Comment by metan-ucw** [comment]
Sure sounds good.

Also I want to replace the json parser with much simpler code later on see https://github.com/metan-ucw/ujson.

**Comment by RobLoach** [comment]
That's a great idea! JSON-C is great, but can be difficult to compile. The other JSON parser that I've seem pop up frequently is https://github.com/kgabis/parson . Nice work on ujson, it looks very clean and minimalistic.

**Comment by metan-ucw** [comment]
Btw I've finished UJSON this evening, added support for floats, bools, etc. and also made sure that it passes the JSONTestSuite.

**Comment by metan-ucw** [comment]
Fixed in 21f3164744eb10da

**Comment by RobLoach** [comment]
Nice work. This is fantastic to see.
