### ISSUE TITLE
Add build .gen.* files to the repository?

### ISSUE THREAD

**Issue by RobLoach** [gfxprim/gfxprim#29]
I was able to build the .gen.h and .gen.c files. But needed a bit of working around to get python to function properly. Was wondering if you would find if they were added to the repository as it would make compiling gfxprim a lot easier.

**Comment by metan-ucw** [comment]
I do not think that this is a good idea.

These are generated based on gfxprim_config.py which is something user is supposed to customize when building for small/embedded platform. There are a few pixel types that are strictly required but quite a lot can be disabled to make the library smaller.
