### ISSUE TITLE
Makefile: Just run CCT?

### ISSUE THREAD

**Issue by RobLoach** [gfxprim/gfxprim#47]
Is there a way to just generate the CCT files without compiling them?

**Comment by metan-ucw** [comment]
Not yet unfortunately, I do have this on my TODO with low priority though. Should be reasonably easy to add to the build system too.

**Comment by metan-ucw** [comment]
Implemented in 99385a4 please test.

**Comment by RobLoach** [comment]
Thanks so much! Will check it out later on.

**Comment by RobLoach** [comment]
This worked well! Thanks a lot.
