### ISSUE TITLE
Show app info also in GUI

### ISSUE THREAD

**Issue by pevik** [gfxprim/gfxprim#51]
Testing on https://github.com/gfxprim/gpmaps/commit/33f2a63a944e7dd95446740a27d1e7b2da7b8243, `-i` shows app info on command line. Is there a way to show it also in GUI? I wonder if it's lack of API or just not implemented in gpmaps.

**Comment by metan-ucw** [comment]
It's described in the commit message a4b2b88eca01c988dcb8fa5376031f6b110edb1e press Ctrl+i to show the app info dialog.

Also all global key bindings are set in https://github.com/gfxprim/gfxprim/blob/master/include/widgets/gp_widget_keys.h

I guess it should be also documented in the docs at http://gfxprim.ucw.cz/widgets.html

**Comment by metan-ucw** [comment]
And the documentation is now at http://gfxprim.ucw.cz/widgets_app_info.html
