### ISSUE TITLE
Build port for Windows

### ISSUE THREAD

**Issue by gAndy50** [gfxprim/gfxprim#52]
Hello,

Would it be possible to have a build port for Windows with a DLL? I saw a build port to other OS was started.

**Comment by metan-ucw** [comment]
It is true that I have started to shuffle things a bit to work on FreeRTOS port, however that does not mean that Windows port will magically appear. I never did any Windows development and I do not plan to work on that at all. The changes I'm doing may make it easier to port the library to different OSes however my plans are limited FreeRTOS and Linux.

**Comment by gAndy50** [comment]
Ah, I see. Well there's always the Linux Subsystem on Windows.

**Comment by RobLoach** [comment]
@gAndy50 In addition, it is possible to use parts of gfxprim. I've compiled parts of it into this libretro core: https://github.com/robloach/libretro-gfxprim
